CRUD MVC/Models/Contact.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CRUD_MVC.Models
{
    public class Contact
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Le nom est requis.")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Le prénom est requis.")]
        public string LastName { get; set; }
        [Required(ErrorMessage = "Le numéro de téléphone est requis.")]

        public string Phone { get; set; }

        public string Email { get; set; }

    }
}

CRUD MVC/Models/ErrorViewModel.cs
using System;

namespace CRUD_MVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CRUD MVC/Controllers/ContactController.cs
using CRUD_MVC.Data;
using CRUD_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CRUD_MVC.Controllers
{
    public class ContactController : Controller
    {
        private readonly ILogger<ContactController> _logger;
        private readonly DataContext _db;

        public ContactController(ILogger<ContactController> logger, DataContext db)
        {
            _db = db;
            _logger = logger;

        }

        public async Task<IActionResult> Index()
        {

            var result = await _db.Contacts.ToListAsync();

            return View(result);
        }


        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Contact contact)
        {
            if (ModelState.IsValid)
            {
                _db.Contacts.Add(contact);
                await _db.SaveChangesAsync();
                TempData["success"] = "Création effectué avec succès";
                return RedirectToAction("Index");
            }
            return View(contact);
        }

        public async Task<IActionResult> Edit(int? id)
        {

            if (id == null || id == 0)
            {
                return NotFound();
            }

            var contact = await _db.Contacts.FindAsync(id);

            if (contact == null)
            {
                return NotFound();
            }


            return View(contact);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Contact contact, int id)
        {
            if (id != contact.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                _db.Contacts.Update(contact);
                await _db.SaveChangesAsync();
                TempData["success"] = "Mise à jour effectué avec succès";
                return RedirectToAction("Index");
            }
            return View(contact);
        }

        public async Task<IActionResult> Delete(int? id)
        {

            if (id == null || id == 0)
            {
                return NotFound();
            }

            var contact = await _db.Contacts.FindAsync(id);

            if (contact == null)
            {
                return NotFound();
            }

            _db.Contacts.Remove(contact);
            await _db.SaveChangesAsync();
            TempData["success"] = "Suppresson effectué avec succès";
            return RedirectToAction("Index");



        }
    }
}

CRUD MVC/Controllers/HomeController.cs
using CRUD_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace CRUD_MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CRUD MVC/Views/Contact/Edit.cshtml
@model Contact;
@{
    ViewData["Title"] = "Edit";
}

<form method="post">
    <div class="form-group">
        <label asp-for="FirstName">Nom</label>
        <input asp-for="FirstName" type="text" class="form-control" placeholder="Veuillez saisir votre nom">
        <span asp-validation-for="FirstName" class="form-text text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="LastName">Prénoms</label>
        <input asp-for="LastName" type="text" class="form-control" placeholder="Veuillez saisir votre nom">
        <span asp-validation-for="LastName" class="form-text text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Phone">Téléphone</label>
        <input asp-for="Phone" type="text" class="form-control" placeholder="Veuillez saisir votre numéro de téléphone">
        <small asp-validation-for="Phone" class="form-text text-danger"></small>
    </div>
    <div class="form-group">
        <label asp-for="Email">Email address</label>
        <input asp-for="Email" type="email" class="form-control" placeholder="Veuillez saisir votre numéro de téléphone">
        <small asp-validation-for="Email" class="form-text text-danger"></small>
    </div>
    <button type="submit" class="btn btn-primary" value="Create">Modifier</button>
</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

CRUD MVC/Views/Contact/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    @model IEnumerable<Contact>

}

<div>
    <div><a class="btn btn-primary mb-2" asp-controller="Contact" asp-action="Create">Nouveau Contact</a></div>
</div>



<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Nom</th>
            <th scope="col">Prénoms</th>
            <th scope="col">Téléphone</th>
            <th scope="col">Email</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Contact contact in Model)
        {

            <tr>
                <td>##</td>
                <td>@contact.FirstName</td>
                <td>@contact.LastName</td>
                <td>@contact.Phone</td>
                <td>@contact.Email</td>
                <td>
                    @{
                        var modal = "#" + "" + @contact.FirstName;
                    }

                    <a class="btn btn-warning" asp-controller="Contact" asp-action="Edit" asp-route-id="@contact.Id"><i class="bi bi-pencil-square"></i></a>
                    <button type="button" class="btn btn-danger" data-toggle="modal" data-target=@modal><i class="bi bi-trash-fill"></i></button>

                    <div class="modal fade" id=@contact.FirstName tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header"><h5 class="modal-title" id="exampleModalLabel">Suppression contact... </h5></div>
                                <div class="modal-body">Voulez-vous supprimer le contact <b>@contact.FirstName @contact.LastName</b>  ?</div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                                    <a asp-controller="Contact" asp-action="Delete" asp-route-id="@contact.Id" class="btn btn-primary">Valider</a>
                                </div>
                            </div>
                        </div>
                    </div>

                </td>

            </tr>
        }

    </tbody>
</table>

CRUD MVC/Views/Contact/create.cshtml
@model Contact;
@{
    ViewData["Title"] = "Create";
}

<form method="post">
    <div class="form-group">
        <label asp-for="FirstName">Nom</label>
        <input asp-for="FirstName" type="text" class="form-control" placeholder="Veuillez saisir votre nom">
        <span asp-validation-for="FirstName" class="form-text text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="LastName">Prénoms</label>
        <input asp-for="LastName" type="text" class="form-control" placeholder="Veuillez saisir votre nom">
        <span asp-validation-for="LastName" class="form-text text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Phone">Téléphone</label>
        <input asp-for="Phone" type="text" class="form-control" placeholder="Veuillez saisir votre numéro de téléphone">
        <span asp-validation-for="Phone" class="form-text text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Email">Email address</label>
        <input asp-for="Email" type="email" class="form-control" placeholder="Veuillez saisir votre numéro Email">
        <span asp-validation-for="Email" class="form-text text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary" value="Create">Ajouter</button>
</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

CRUD MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CRUD MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CRUD_MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">

    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Contact" asp-action="Index">Contact 2.0</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - eroambahub.com - <a asp-area="" asp-controller="Contact" asp-action="Index">CRUD ASP.NET Core</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>